services:
  currencyexchangeratesapi:
    image: currencyexchangeratesapi
    build:
      context: .
      dockerfile: CurrencyExchangeRatesApi/Dockerfile
    env_file:
      - .env
    depends_on:
      - sqlserver
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: currencyexchangeratesapi_sqlserver
    user: root
    environment:
      - MSSQL_PID=Standard
      - MSSQL_DB=Currency_Exchange_Rates
      - SA_PASSWORD=sa
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver_system:/var/opt/mssql/data
      - sqlserver_data:/data
    ports:
      - 1450:1433
    profiles:
      - sqlserver
    command:
      - /bin/bash
      - -c
      - |
        (echo "Database started") &
        /opt/mssql/bin/permissions_check.sh /opt/mssql/bin/sqlservr


