services:
  currencyexchangerates.api:
    image: ${DOCKER_REGISTRY-}currencyexchangeratesapi
    build:
      context: .
      dockerfile: CurrencyExchangeRates.Api/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      sqlserver:
        condition: service_healthy